version: "3.8"

services:
######################################################
# DATABASE SERVICE
######################################################
  airflow-metastore:
    image: postgres:13.1-alpine
    restart: always
    container_name: airflow-metastore
    volumes:
      - ./mnt/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - pgsite
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow" ]
      timeout: 45s
      interval: 10s
      retries: 10

networks:
  pgsite:
    driver: bridge